apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: teams
spec:
  targets:
    - https://github.com/atosBackStage/Example3BackstageAPI/blob/main/catalog-info.yaml
  filter:
    kind:
      - User
      - Group
