apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: teams
spec:
  targets:
    - url: https://github.com/atosBackStage/Example3BackstageAPI/blob/main/catalog-info.yaml
      allowedKinds: [User, Group]
